name: Build
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup checkOut
      uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Build solution
      run: msbuild .\PhysicsGame.sln /p:Configuration=Release
    - name: Run dir
      run: dir
